### ISSUE TITLE
snoing rat-4.5.0 on a mac

### ISSUE THREAD

**Issue by knapik** [snoplus/snoing#126]
I have a quick question/comment about using snoing for RAT 4.5.0 on Mac OS X

I heard  that there is something tricky that has to be done and based on my 
attempts, it looks like the openmotif library is the issue. I used 
macports to install openmotif and  I have Xm/Xm.h installed under 
/opt/local/include/

sudo ln -sf /opt/local/include/Xm /usr/OpenMotif/

seemed to do the trick and snoing  has moved on from the check for Xm/Xm.h  
It is now installing geant4.9.6.p02, so I have some time to kill.  

Are there any other issues that people know about?

Thanks, 
rob

**Comment by kgilje** [comment]
This issue is deprecated.  We no longer support Mac installs with RAT.
