### ISSUE TITLE
XSNOED and Dispatcher

### ISSUE THREAD

**Issue by krishmaj** [snoplus/snoing#130]
At the moment, the installation of XSNOED doesn't come as standard with the Dispatcher, and the Dispatcher files that the user manual points to aren't compatible with 64-bit systems.  I've managed to get the Dispatcher working with Oxford's 64-bit system by doing the following:

1) first, get the Dispatcher libraries from: https://github.com/snoplus/disp (which can be compiled on 64-bit, instead of the pre-compiled-on-32-bit tarball from surf.sno.laurentian.ca as indicated by the manual), and make two copies ... one located in the snoing installation folder, and the other located in rattools-dev/ratzdab/contrib (both copies need to be compiled).

2) second, install and make the xsnoed-dev package (both of the disp folders need to be in place before this, otherwise the installation fails to make)

3) add the following line to the env_xsnoed-dev scripts:

export LD_LIBRARY_PATH=[snoing installation path]/disp/lib:$LD_LIBRARY_PATH

(for the .sh file, and whatever the equivalent is for .csh) so that xsnoed knows where the libraries are (for some reason it can't find them on its own, even after make-ing xsnoed correctly).

I think all of this should go into the snoing installation of XSNOED as standard, unless there is a reason why the dispatcher shouldn't be installed by default.  (I don't know how to change things myself though, which is why this is an issue rather than a pull request!)

**Comment by kgilje** [comment]
Fixed by Pull Request #149
