### ISSUE TITLE
Root Compilation

### ISSUE THREAD

**Issue by kgilje** [snoplus/snoing#144]
The current root compilation uses the ./configure make method.  The makers of root recommend the cmake method now.  As we are thinking about moving to root 6 it might be a good time to switch.

**Comment by kgilje** [comment]
As a followup, I've been working on installing root on cedar (the new compute canada node).  The only way I was able to install root 5 myself was through cmake.  The configure method was not able to find certain system libraries that were in unusual places (ie not in /usr/lib).  Thanks.

**Comment by parnmatt** [comment]
I am currently working on changes to move forward with the upcoming large version change, cake included.

We've only once had an issue with ROOT 5 using the legacy make system with just one Mac, which had similar issues and solved using cmake. No other issues had arisen, thought it was a one off.

OK well I will go through and try and get something more concretely in place in a shorter time span.

**Comment by kgilje** [comment]
The cmake command needed some extra direction to find any snoing install of gsl and fftw.  I think this has been addressed in PR #149
