### ISSUE TITLE
RAT 6.5.0

### ISSUE THREAD

**Issue by estherturner** [snoplus/snoing#146]
When running snoing to download water RAT, it fails doing ./snoing.py -q with the following error:

Traceback (most recent call last):
  File "./snoing.py", line 128, in <module>
    package_manager.register_packages(os.path.join(os.path.dirname(__file__), "versions"))
  File "/data/snoplus/software/snoing/core/packagemanager.py", line 46, in register_packages
    self.register_package(obj)
  File "/data/snoplus/software/snoing/core/packagemanager.py", line 30, in register_package
    instance = package(self._system)
  File "/data/snoplus/software/snoing/versions/ratversions.py", line 43, in __init__
    super(RAT643, self).__init__("rat-6.5.0", system, "root-5.34.36", "6.5.0")
TypeError: super(type, obj): obj must be an instance or subtype of type

The problem is here, I believe, where RAT643 is called instead:

class RAT650OSX(ratreleases.RatRelease6):
    """ Rat release-6.5.0-OSX, install package."""
    def __init__(self, system):
        """ Initiliase the rat 6.5.0-OSX package."""
        super(RAT643, self).__init__("rat-6.5.0-OSX", system, "root-5.34.36", "6.5.0-OSX")

class RAT650(ratreleases.RatRelease6):
    """ Rat release-6.5.0, install package."""
    def __init__(self, system):
        """ Initiliase the rat 6.5.0 package."""
        super(RAT643, self).__init__("rat-6.5.0", system, "root-5.34.36", "6.5.0")

**Comment by parnmatt** [comment]
Ah! My bad; thanks for pointing it out.
That's exactly the issue you're seeing. I hate the old Python 2 syntax for `super`, it's very much prone to mistakes like those.
Fixed in d507ec35e11822e37cd3ce8704480a501dc73a15, just resource `env.sh` and you should be fine to go.
