### ISSUE TITLE
Installation of rat-dev

### ISSUE THREAD

**Issue by akselhallin** [snoplus/snoing#148]
I tried to install a version of rat-dev on a new computer.  One runs into multiple issues:

1.  With the snoing install, it tried to install bzip2.  What is built into the code is a website http://www.bzip.org/ which no longer exists.  I (eventually) got around this by installing bzip2-devel onto my system; in which case it no longer tries to download.
2.  In working through this, I did try to manually install the individual requirements for rat.  I ran into problems with postresql; and while I installed several packages, was not able to get this to work.

**Comment by kgilje** [comment]
Fixed by PR #149
